import type { Metadata } from "next"

import { PageContainer } from "@/components/layout/page-container"
import { SectionHeading } from "@/components/layout/section-heading"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

export const metadata: Metadata = { title: "Research notes" }

export default function ResearchPage() { return <PageContainer className="pb-16 pt-10 sm:pt-14"><SectionHeading eyebrow="Research notes" title="Read the market with useful skepticism" description="This page records the questions CompGrid is built to help answer, plus the caveats that should travel with every chart." /><div className="mt-8 grid gap-5 lg:grid-cols-[1.15fr_0.85fr]"><Card><CardHeader><CardTitle>What we are investigating</CardTitle></CardHeader><CardContent><div className="space-y-5 text-sm leading-7 text-muted-foreground"><p><span className="font-semibold text-foreground">Level equivalence.</span> The same-looking title can represent different scope, interview bars, and geographic bands. Company ladders are therefore mapped directionally and remain visible beside the canonical level.</p><p><span className="font-semibold text-foreground">Package mix.</span> Base salary is easier to compare than equity, especially when grant value, vesting, refreshers, and liquidity differ. Stock is shown as an annual estimate and should not be read as cash.</p><p><span className="font-semibold text-foreground">Location premiums.</span> City-level medians can reflect role mix and sample mix as much as a true location effect. Filters are designed to make those confounders inspectable.</p></div></CardContent></Card><Card><CardHeader><CardTitle>Competitor context</CardTitle></CardHeader><CardContent><div className="space-y-4 text-sm"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">Public salary aggregators</p><p className="mt-1 leading-6 text-muted-foreground">Broad coverage, inconsistent level semantics.</p></div><Badge variant="outline">Context</Badge></div><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">Offer communities</p><p className="mt-1 leading-6 text-muted-foreground">High-signal anecdotes, often small and selection-biased.</p></div><Badge variant="outline">Context</Badge></div><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">Company review platforms</p><p className="mt-1 leading-6 text-muted-foreground">Useful employer sentiment; compensation may be less granular.</p></div><Badge variant="outline">Context</Badge></div></div></CardContent></Card></div><div className="mt-8 rounded-2xl border border-warning/30 bg-warning/10 p-5 text-sm leading-7"><strong>Disclosure:</strong> The current local/demo dataset is synthetic and deterministic. It is included to demonstrate the product model and should not be used for negotiation, financial decisions, or claims about any employer.</div></PageContainer> }
