import type { Metadata } from "next"

import { PageContainer } from "@/components/layout/page-container"
import { SectionHeading } from "@/components/layout/section-heading"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

export const metadata: Metadata = { title: "Methodology" }

const principles = [{ title: "Normalize before comparing", body: "Names, aliases, cities, currencies, and compensation components are normalized at ingestion. Total compensation is derived as base salary plus annualized stock and bonus." }, { title: "Map levels, preserve titles", body: "Company-specific levels stay intact. A separate canonical career level provides a cautious comparison axis across ladders such as Google L4, Amazon L5, and Microsoft 63." }, { title: "Show distributions", body: "Median, quartiles, p90, minimum, maximum, and record count are more useful than a single advertised number. Small samples should be read as directional." }, { title: "Keep the data boundary clear", body: "Demo records are deterministic and labeled. Public submissions are anonymous and initially unverified. CompGrid is an intelligence layer, not an offer validator." }]

export default function MethodologyPage() { return <PageContainer className="pb-16 pt-10 sm:pt-14"><SectionHeading eyebrow="How it works" title="A transparent compensation model" description="CompGrid is designed to make assumptions visible, not to hide uncertainty behind polished numbers." /><div className="mt-8 grid gap-4 sm:grid-cols-2">{principles.map((item, index) => <Card key={item.title}><CardHeader><p className="text-xs font-bold tracking-[0.14em] text-primary">0{index + 1}</p><CardTitle>{item.title}</CardTitle></CardHeader><CardContent><p className="text-sm leading-7 text-muted-foreground">{item.body}</p></CardContent></Card>)}</div><section className="mt-10 rounded-2xl border border-border/80 bg-secondary/45 p-5 sm:p-7"><h2 className="font-heading text-xl font-bold">Metric definitions</h2><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="font-semibold">Total compensation</dt><dd className="mt-1 leading-6 text-muted-foreground">Base salary + annual stock/equity + annual bonus, stored as integer INR.</dd></div><div><dt className="font-semibold">Median</dt><dd className="mt-1 leading-6 text-muted-foreground">The 50th percentile of matching records; less sensitive to an unusually high offer.</dd></div><div><dt className="font-semibold">Canonical level</dt><dd className="mt-1 leading-6 text-muted-foreground">A directional shared ladder used for browsing and comparison, never a guarantee of scope.</dd></div><div><dt className="font-semibold">Verified</dt><dd className="mt-1 leading-6 text-muted-foreground">A moderation state. Demo data is not presented as verified community evidence.</dd></div></dl></section></PageContainer> }
